apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: green
  name: green
spec:
  replicas: 1
  selector:
    matchLabels:
      app: green
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: green
    spec:
      nodeName: NODE
      containers:
      - command:
        - "/bin/bash"
        - "-x"
        - "/entrypoint/green.sh"
        image: IMAGE
        imagePullPolicy: IfNotPresent
        name: reproducer
        volumeMounts:
        - name: entrypoint
          mountPath: /entrypoint
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
            - NET_RAW
            - SYS_ADMIN
            - NET_BIND_SERVICE
          privileged: true
        env:
        - name: SENDER_MTU
          value: "SENDER_MTU_VALUE"
        - name: IP_AF
          value: "IP_AF_VALUE"
      volumes:
      - name: entrypoint
        configMap:
          name: entrypoint
